HIGHFIVE/Assets/Scenes/04.SelectScene.unity
HIGHFIVE/Assets/Scripts/Scene/SelectScene.cs
HIGHFIVE/Assets/Scripts/UI.meta
HIGHFIVE/Assets/Scripts/UI/Popup_UI.meta
HIGHFIVE/Assets/Scripts/UI/Scene_UI.meta
HIGHFIVE/Assets/Scripts/UI/Scene_UI/Test_UI.cs
HIGHFIVE/Assets/Scripts/UI/Scene_UI/Test_UI.cs.meta
HIGHFIVE/Assets/Scripts/UI/UIBase.cs
HIGHFIVE/Assets/Scripts/UI/UIBase.cs.meta
HIGHFIVE/Assets/Scripts/Utils/Util.cs
HIGHFIVE/Assets/Scripts/Utils/Util.cs.meta

[💫 Feat] UI_Binding

---

HIGHFIVE/Assets/Plugins/Borodar/RainbowFolders/Editor/Source/RainbowFolders.src.unitypackage.meta
HIGHFIVE/Assets/Scripts/Photon/Launcher.cs

[Test] Photon Lobby Info Test

---

HIGHFIVE/Assets/Scripts/EventHandler/Photon/PhotonHandler.cs
HIGHFIVE/Assets/Scripts/Managers/DataManager.cs
HIGHFIVE/Assets/Scripts/Managers/NetworkManager.cs
HIGHFIVE/Assets/Scripts/Scene/BaseScene.cs
HIGHFIVE/Assets/Scripts/UI/Scene_UI/LobbyScene_UI.cs
HIGHFIVE/Assets/Scripts/UI/Scene_UI/RoomPlayerManager.cs
HIGHFIVE/Assets/Scripts/UI/Scene_UI/RoomScene_UI.cs

포톤 로비에서 방에서 들어갔다 나왔을때 방이 한번 더 찍히는 버그 수정

[Bug Fix] PhotonLobby

---

HIGHFIVE/Assets/Resources/Prefabs/UI_Prefabs/Player.prefab
HIGHFIVE/Assets/Resources/Prefabs/UI_Prefabs/Player.prefab.meta
HIGHFIVE/Assets/Scenes/02.LobbyScene.unity
HIGHFIVE/Assets/Scenes/03.RoomScene.unity
HIGHFIVE/Assets/Scripts/EventHandler/Photon/PhotonHandler.cs
HIGHFIVE/Assets/Scripts/UI/Scene_UI/LobbyScene_UI.cs
HIGHFIVE/Assets/Scripts/UI/Scene_UI/RoomPlayerManager.cs
HIGHFIVE/Assets/Scripts/UI/Scene_UI/RoomScene_UI.cs

[Bug Fix] Photon Sync

---

HIGHFIVE/Assets/Plugins/Borodar/RainbowFolders/Editor/Source/RainbowFolders.src.unitypackage.meta
HIGHFIVE/Assets/Scenes/04.SelectScene.unity

[Mod] Player Ready Btn Delete

---

HIGHFIVE/Assets/Resources/Prefabs/UI_Prefabs/AlertBlock.prefab
HIGHFIVE/Assets/Resources/Prefabs/UI_Prefabs/AlertBlock.prefab.meta
HIGHFIVE/Assets/Scenes/02.LobbyScene.unity
HIGHFIVE/Assets/Scenes/03.RoomScene.unity
HIGHFIVE/Assets/Scripts/Managers/Main.cs
HIGHFIVE/Assets/Scripts/Managers/NetworkManager.cs
HIGHFIVE/Assets/Scripts/Managers/ObjectManager.cs
HIGHFIVE/Assets/Scripts/Managers/ObjectManager.cs.meta
HIGHFIVE/Assets/Scripts/Managers/UIManager.cs
HIGHFIVE/Assets/Scripts/UI/Popup_UI/SetRoomUI.cs
HIGHFIVE/Assets/Scripts/UI/Popup_UI/SetRoomUI.cs.meta
HIGHFIVE/Assets/Scripts/UI/Scene_UI/LobbyScene_UI.cs
HIGHFIVE/Assets/Scripts/UI/Scene_UI/RoomScene_UI.cs
HIGHFIVE/Assets/Scripts/Utils/Define.cs
HIGHFIVE/Assets/Scripts/Utils/Util.cs

[Feat] Add Room Setting

---

HIGHFIVE/Assets/Resources/Prefabs/UI_Prefabs/AlertBlock.prefab
HIGHFIVE/Assets/Scenes/02.LobbyScene.unity

[Fix] UI Sizing

---

HIGHFIVE/Assets/Plugins/Borodar/RainbowFolders/Editor/Source/RainbowFolders.src.unitypackage.meta
HIGHFIVE/Assets/Resources/TestMapSprites/Pixel Art Top Down - Basic/Tile Palette/TP Grass.prefab
HIGHFIVE/Assets/Resources/TestMapSprites/Pixel Art Top Down - Basic/Tile Palette/TP Stone Ground.prefab
HIGHFIVE/Assets/Scripts/UI/Scene_UI/LobbyScene_UI.cs

[Fix Bug] Lobby Info Sync

---

HIGHFIVE/Assets/Scripts/UI/Scene_UI/LobbyScene_UI.cs

방장이 방 만들고 나갔을 때 Null 에러가 뜨는 오류 수정

[Fix] Null Error Fix

---

HIGHFIVE/Assets/Scripts/Interface/IState.cs
HIGHFIVE/Assets/Scripts/State/Character/PlayerBaseState.cs
HIGHFIVE/Assets/Scripts/StateMachine/StateMachine.cs

[Fix] Code Convention

---

HIGHFIVE/Assets/Scripts/Object/Monster/Monster.cs
HIGHFIVE/Assets/Scripts/Object/Monster/Monster.cs.meta
HIGHFIVE/Assets/Scripts/State/Monster/MonsterAnimationData.cs
HIGHFIVE/Assets/Scripts/State/Monster/MonsterAnimationData.cs.meta
HIGHFIVE/Assets/Scripts/State/Monster/MonsterAttackState.cs
HIGHFIVE/Assets/Scripts/State/Monster/MonsterAttackState.cs.meta
HIGHFIVE/Assets/Scripts/State/Monster/MonsterBaseState.cs
HIGHFIVE/Assets/Scripts/State/Monster/MonsterBaseState.cs.meta
HIGHFIVE/Assets/Scripts/State/Monster/MonsterDieState.cs
HIGHFIVE/Assets/Scripts/State/Monster/MonsterDieState.cs.meta
HIGHFIVE/Assets/Scripts/State/Monster/MonsterIdleState.cs
HIGHFIVE/Assets/Scripts/State/Monster/MonsterIdleState.cs.meta
HIGHFIVE/Assets/Scripts/State/Monster/MonsterMoveState.cs
HIGHFIVE/Assets/Scripts/State/Monster/MonsterMoveState.cs.meta
HIGHFIVE/Assets/Scripts/StateMachine/Monster/MonsterStateMachine.cs
HIGHFIVE/Assets/Scripts/StateMachine/Monster/MonsterStateMachine.cs.meta

[Feat] MonsterFSM Creative

---

HIGHFIVE/Assets/Resources/Animations/CharacterController/CharacterAnimController.controller
HIGHFIVE/Assets/Scripts/State/Character/PlayerMoveState.cs

[Fix] Animation Parameter

---

HIGHFIVE/Assets/Plugins/Borodar/RainbowFolders/Editor/Source/RainbowFolders.src.unitypackage.meta
HIGHFIVE/Assets/Scenes/PlayerTestScene.unity
HIGHFIVE/Assets/Scripts/State/Character/PlayerAttackState.cs
HIGHFIVE/Assets/Scripts/State/Character/PlayerBaseState.cs
HIGHFIVE/Assets/Scripts/State/Character/PlayerDieState.cs
HIGHFIVE/Assets/Scripts/State/Character/PlayerIdleState.cs
HIGHFIVE/Assets/Scripts/State/Character/PlayerMoveState.cs
HIGHFIVE/Assets/Scripts/StateMachine/Character/PlayerStateMachine.cs
HIGHFIVE/ProjectSettings/TagManager.asset

[Feat] Character Attack

---

HIGHFIVE/Assets/Resources/Data/HIGHFIVE_Data.asset
HIGHFIVE/Assets/Resources/Prefabs/Monster.meta
HIGHFIVE/Assets/Resources/Prefabs/Monster/Enemy.prefab
HIGHFIVE/Assets/Resources/Prefabs/Monster/Enemy.prefab.meta
HIGHFIVE/Assets/Scenes/LSC_MonsterFSMTest.unity
HIGHFIVE/Assets/Scripts/Content/Stat/Monster/TreeStat.cs
HIGHFIVE/Assets/Scripts/Data/MonsterDBEntity.cs
HIGHFIVE/Assets/Scripts/State/Monster/MonsterBaseState.cs
HIGHFIVE/Assets/Scripts/State/Monster/MonsterMoveState.cs

이제 Collider는 인식을 하지만 따라가는 로직이 있음에도 안되는걸 보아하니 오류가 있는 듯함.

[fix] MonsterFSM

---

HIGHFIVE/Assets/Plugins/Borodar/RainbowFolders/Editor/Source/RainbowFolders.src.unitypackage.meta
HIGHFIVE/Assets/Scenes/YGH_GameScene.unity
HIGHFIVE/Assets/Scripts/Content/Camera/CameraMover.cs
HIGHFIVE/Assets/Scripts/YGH/Test_RoundLogic.cs
HIGHFIVE/Assets/Scripts/YGH/Test_RoundTimer.cs
HIGHFIVE/ProjectSettings/EditorBuildSettings.asset

[Fix] Timer

---

HIGHFIVE/Assets/Plugins/Borodar/RainbowFolders/Editor/Source/RainbowFolders.src.unitypackage.meta
HIGHFIVE/Assets/Resources/TestMapSprites/Pixel Art Top Down - Basic/Tile Palette/TP Grass.prefab
HIGHFIVE/Assets/Scripts/Content/Weapon/MageWeapon.cs
HIGHFIVE/Assets/Scripts/EventHandler/Photon/PhotonHandler.cs
HIGHFIVE/Assets/Scripts/Object/Character/Character.cs
HIGHFIVE/Assets/Scripts/State/Character/PlayerInput.cs
HIGHFIVE/Assets/Scripts/State/Character/PlayerMoveState.cs
HIGHFIVE/Assets/Scripts/UI/Scene_UI/LobbyScene_UI.cs
HIGHFIVE/Assets/Scripts/UI/World_UI/HealthBar.cs

[Mod] Remove Debug & Code

---

HIGHFIVE/Assets/Resources/Animations/MonsterController_Treant.controller

[fix] Tree Animation Attack fix

---

HIGHFIVE/Assets/Resources/Prefabs/Monster/Enemy.prefab
HIGHFIVE/Assets/Scripts/Content/Weapon/MageWeapon.cs

[Fix] Prefab Layer Tag

---

HIGHFIVE/Assets/Plugins/Borodar/RainbowFolders/Editor/Source/RainbowFolders.src.unitypackage.meta
HIGHFIVE/Assets/Resources/Animations/MonsterController_Treant.controller
HIGHFIVE/Assets/Resources/Animations/Treant_Die.anim
HIGHFIVE/Assets/Resources/Prefabs/Monster/Enemy.prefab
HIGHFIVE/Assets/Resources/TestMapSprites/Pixel Art Top Down - Basic/Tile Palette/TP Grass.prefab
HIGHFIVE/Assets/Scenes/LSC_MonsterFSMTest.unity
HIGHFIVE/Assets/Scripts/Content/Weapon/MageWeapon.cs
HIGHFIVE/Assets/Scripts/Object/Monster/Revival.cs
HIGHFIVE/Assets/Scripts/Object/Monster/Revival.cs.meta
HIGHFIVE/Assets/Scripts/State/Monster/MonsterAnimationData.cs
HIGHFIVE/Assets/Scripts/State/Monster/MonsterDieState.cs

[Feat] Monster Spawn

---

HIGHFIVE/Assets/Scripts/Content/Stat/Character/CharacterStat.cs
HIGHFIVE/Assets/Scripts/Content/Stat/Stat.cs
HIGHFIVE/Assets/Scripts/Content/Weapon/MageWeapon.cs
HIGHFIVE/Assets/Scripts/Object/Monster/Revival.cs
HIGHFIVE/Assets/Scripts/State/Monster/MonsterDieState.cs

타겟을 지정한 오브젝트에 투사체를 날릴 때 중간에 다른 오브젝트와 충돌 했을 때 에러가 나는 오류 수정 몬스터가 죽었을 때 한번 더 때리면 경험치가 한번 더 오르는 버그 수정

[Fix] targeting  & Exp

---

HIGHFIVE/Assets/Scripts/Content/Stat/Character/CharacterStat.cs
HIGHFIVE/Assets/Scripts/Content/Stat/Monster/MonsterSpawner.cs
HIGHFIVE/Assets/Scripts/Content/Weapon/MageWeapon.cs
HIGHFIVE/Assets/Scripts/Managers/UIManager.cs
HIGHFIVE/Assets/Scripts/UI/World_UI/HealthBar.cs

[Fix] Charater Damage

---

HIGHFIVE/Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
HIGHFIVE/Assets/Resources/TestMapSprites/Pixel Art Top Down - Basic/Tile Palette/TP Grass.prefab
HIGHFIVE/Assets/Scripts/Content/Weapon/MageWeapon.cs
HIGHFIVE/Assets/Scripts/Object/Monster/Tree.cs
HIGHFIVE/Assets/Scripts/State/Monster/MonsterDieState.cs

[Test] Monster Die Sync Test

---

HIGHFIVE/Assets/Resources/Prefabs/Monster/Enemy.prefab
HIGHFIVE/Assets/Resources/TestMapSprites/Pixel Art Top Down - Basic/Tile Palette/TP Grass.prefab
HIGHFIVE/Assets/Scripts/Content/Stat/Monster/MonsterSpawner.cs
HIGHFIVE/Assets/Scripts/Managers/ResourceManager.cs
HIGHFIVE/Assets/Scripts/Object/Character/Mage.cs
HIGHFIVE/Assets/Scripts/Object/Monster/Tree.cs
HIGHFIVE/Assets/Scripts/State/Monster/MonsterDieState.cs

[Feat] moster die Sync

---

HIGHFIVE/Assets/Scripts/Content/Weapon/MageWeapon.cs
HIGHFIVE/Assets/Scripts/Object/Monster/Monster.cs
HIGHFIVE/Assets/Scripts/Object/Monster/Tree.cs

[Fix] hp Sync

---

HIGHFIVE/Assets/Scenes/05.GameScene.unity

[Fix] Change Spawn Position

---

HIGHFIVE/Assets/Plugins/Borodar/RainbowFolders/Editor/Source/RainbowFolders.src.unitypackage.meta
HIGHFIVE/Assets/Resources/Prefabs/Character/Mage.prefab
HIGHFIVE/Assets/Resources/Prefabs/Character/Rogue.prefab
HIGHFIVE/Assets/Resources/Prefabs/Character/Warrior.prefab
HIGHFIVE/Assets/Resources/Prefabs/Monster/Enemy.prefab
HIGHFIVE/Assets/Resources/Prefabs/UI_Prefabs/GameSceneUI.prefab
HIGHFIVE/Assets/Resources/Prefabs/UI_World/HealthCanvas.prefab
HIGHFIVE/Assets/Scripts/Content/Stat/Character/CharacterStat.cs
HIGHFIVE/Assets/Scripts/Content/Stat/Monster/MonsterSpawner.cs
HIGHFIVE/Assets/Scripts/Content/Stat/Stat.cs
HIGHFIVE/Assets/Scripts/Controller/StatController.cs
HIGHFIVE/Assets/Scripts/Object/Character/Character.cs
HIGHFIVE/Assets/Scripts/Object/Character/Mage.cs
HIGHFIVE/Assets/Scripts/Object/Creature.cs
HIGHFIVE/Assets/Scripts/Object/Creature.cs.meta
HIGHFIVE/Assets/Scripts/Object/Monster/Revival.cs
HIGHFIVE/Assets/Scripts/UI/GameScene_UI/SpawnedCharacterStats.cs
HIGHFIVE/Assets/Scripts/UI/World_UI/HealthBar.cs
HIGHFIVE/Assets/Scripts/Utils/Define.cs

캐릭터 스테에 따라 Stat UI에도 반영되게 기능 추가

[Feat] Renewal Stat UI

---

HIGHFIVE/Assets/Resources/Prefabs/UI_World/HealthCanvas.prefab
HIGHFIVE/Assets/Resources/TestMapSprites/Pixel Art Top Down - Basic/Tile Palette/TP Grass.prefab
HIGHFIVE/Assets/Scenes/LSC_MonsterFSMTest.unity
HIGHFIVE/Assets/Scripts/Managers/Main.cs
HIGHFIVE/Assets/Scripts/Managers/SoundManager.cs
HIGHFIVE/Assets/Scripts/Scene/StartScene.cs
HIGHFIVE/Assets/Scripts/UI/World_UI/HealthBar.cs
HIGHFIVE/Assets/Scripts/Utils/Define.cs

[Feat] identification of friend or foe

---

HIGHFIVE/Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
HIGHFIVE/Assets/Resources/Animations/CharacterAnim/CharacterDie.anim
HIGHFIVE/Assets/Resources/Animations/CharacterAnim/CharacterFrontAttack.anim
HIGHFIVE/Assets/Resources/Animations/CharacterController/CharacterAnimController.controller
HIGHFIVE/Assets/Resources/Animations/MonsterController_Treant.controller
HIGHFIVE/Assets/Resources/Animations/Treant_Attack.anim
HIGHFIVE/Assets/Resources/Animations/Treant_Die.anim
HIGHFIVE/Assets/Resources/Prefabs/Character/Mage.prefab
HIGHFIVE/Assets/Resources/TestMapSprites/Pixel Art Top Down - Basic/Tile Palette/TP Grass.prefab
HIGHFIVE/Assets/Resources/TestMapSprites/Pixel Art Top Down - Basic/Tile Palette/TP Stone Ground.prefab
HIGHFIVE/Assets/Scripts/Content/Stat/Stat.cs
HIGHFIVE/Assets/Scripts/Content/Weapon/MageWeapon.cs
HIGHFIVE/Assets/Scripts/Managers/ResourceManager.cs
HIGHFIVE/Assets/Scripts/Object/Character/Character.cs
HIGHFIVE/Assets/Scripts/Object/Character/Mage.cs
HIGHFIVE/Assets/Scripts/Object/Monster/Monster.cs
HIGHFIVE/Assets/Scripts/Object/Monster/Tree.cs
HIGHFIVE/Assets/Scripts/Object/Monster/TreeNormalAttack.cs
HIGHFIVE/Assets/Scripts/State/Character/PlayerAttackState.cs
HIGHFIVE/Assets/Scripts/State/Character/PlayerBaseState.cs
HIGHFIVE/Assets/Scripts/State/Character/PlayerDieState.cs
HIGHFIVE/Assets/Scripts/State/Character/PlayerIdleState.cs
HIGHFIVE/Assets/Scripts/State/Monster/MonsterAttackState.cs
HIGHFIVE/Assets/Scripts/State/Monster/MonsterBaseState.cs
HIGHFIVE/Assets/Scripts/UI/World_UI/HealthBar.cs

[Fix] bug Fix

---

HIGHFIVE/Assets/Plugins/Borodar/RainbowFolders/Editor/Source/RainbowFolders.src.unitypackage.meta
HIGHFIVE/Assets/Resources/Prefabs/Monster/Enemy.prefab
HIGHFIVE/Assets/Resources/TestMapSprites/Pixel Art Top Down - Basic/Tile Palette/TP Grass.prefab
HIGHFIVE/Assets/Scripts/Content/Stat/Monster/MonsterSpawner.cs
HIGHFIVE/Assets/Scripts/Object/Creature.cs
HIGHFIVE/Assets/Scripts/UI/Scene_UI/PlayerListController.cs

[Mod] room Info

---

HIGHFIVE/Assets/Resources/TestMapSprites/Pixel Art Top Down - Basic/Tile Palette/TP Grass.prefab
HIGHFIVE/Assets/Scripts/UI/Scene_UI/RoomScene_UI.cs

게스트가 나갔다 들어왔을 때 준비 상태가 초기화 안되는 버그 수정

[Fix] Game Start Bug

---

HIGHFIVE/Assets/Scripts/Managers/GameManager.cs
HIGHFIVE/Assets/Scripts/Object/Character/Character.cs
HIGHFIVE/Assets/Scripts/Scene/GameScene.cs
HIGHFIVE/Assets/Scripts/Scene/SelectScene.cs
HIGHFIVE/Assets/Scripts/State/Character/PlayerDieState.cs
HIGHFIVE/Assets/Scripts/State/Character/PlayerIdleState.cs
HIGHFIVE/Assets/Scripts/UI/GameScene_UI/RoundLogic.cs
HIGHFIVE/Assets/Scripts/UI/GameScene_UI/RoundTimer.cs
HIGHFIVE/Assets/Scripts/UI/GameScene_UI/ToLobbyBtn.cs
HIGHFIVE/Assets/Scripts/UI/Scene_UI/RoomScene_UI.cs
HIGHFIVE/Assets/Scripts/UI/World_UI/HealthBar.cs
HIGHFIVE/Assets/Scripts/Utils/Define.cs

[Feat] Game Over And To Lobby

---

HIGHFIVE/Assets/Resources/Prefabs/UI_Prefabs/GameSceneUI.prefab
HIGHFIVE/Assets/Resources/Prefabs/UI_World/HealthCanvas.prefab

[Fix] Slider UI Interactable => false

---

HIGHFIVE/Assets/Resources/Data/HIGHFIVE_Data.asset
HIGHFIVE/Assets/Resources/Materials.meta
HIGHFIVE/Assets/Scenes/05.GameScene.unity
HIGHFIVE/Assets/Scripts/Data/BuffDBEntity.cs
HIGHFIVE/Assets/Scripts/Data/BuffDBEntity.cs.meta
HIGHFIVE/Assets/Scripts/Data/HIGHFIVE_Data.cs
HIGHFIVE/Assets/Scripts/Data/SkillDBEntity.cs
HIGHFIVE/Assets/Scripts/UI/GameScene_UI/RoundLogic.cs

[Fix] Camera Move Range Fix

---

HIGHFIVE/Assets/Scenes/05.GameScene.unity

[Fix] GameScene UI

---

HIGHFIVE/Assets/Resources/Prefabs/Character/Test.prefab
HIGHFIVE/Assets/Scenes/05.GameScene.unity

[Fix] Map Rigidbody2d add, Player rigidbody fix

---

HIGHFIVE/Assets/Scenes/05.GameScene.unity

[Fix] RigidBody2D fix

---

HIGHFIVE/Assets/Resources/Prefabs/Character/Test.prefab
HIGHFIVE/Assets/Resources/Prefabs/UI_Prefabs/Buff.prefab
HIGHFIVE/Assets/Resources/Prefabs/UI_Prefabs/Buff.prefab.meta
HIGHFIVE/Assets/Resources/Prefabs/UI_Prefabs/GameSceneUI.prefab
HIGHFIVE/Assets/Scripts/Content/Buff/BaseBuff.cs
HIGHFIVE/Assets/Scripts/Content/Buff/LoserBuff.cs
HIGHFIVE/Assets/Scripts/Content/Buff/LoserBuff.cs.meta
HIGHFIVE/Assets/Scripts/Controller/BuffController.cs
HIGHFIVE/Assets/Scripts/Controller/BuffController.cs.meta
HIGHFIVE/Assets/Scripts/Managers/DataManager.cs
HIGHFIVE/Assets/Scripts/Object/Character/Character.cs
HIGHFIVE/Assets/Scripts/State/Character/PlayerDieState.cs
HIGHFIVE/Assets/Scripts/UI/GameScene_UI/RoundLogic.cs
HIGHFIVE/Assets/Scripts/UI/Scene_UI/BuffScene_UI.cs
HIGHFIVE/Assets/Scripts/UI/Scene_UI/BuffScene_UI.cs.meta

[Feat] Buff System

---

HIGHFIVE/Assets/Scripts/Content/Buff/BaseBuff.cs
HIGHFIVE/Assets/Scripts/Content/Buff/LoserBuff.cs
HIGHFIVE/Assets/Scripts/Controller/BuffController.cs
HIGHFIVE/Assets/Scripts/UI/GameScene_UI/RoundLogic.cs
HIGHFIVE/Assets/Scripts/UI/Scene_UI/BuffScene_UI.cs

[Mod] Method Name

---

HIGHFIVE/Assets/Resources/Prefabs/Character/FireBall.prefab
HIGHFIVE/Assets/Resources/Prefabs/UI_Prefabs/GameSceneUI.prefab
HIGHFIVE/Assets/Resources/Prefabs/UI_Prefabs/Skill.prefab
HIGHFIVE/Assets/Resources/Prefabs/UI_Prefabs/Skill.prefab.meta
HIGHFIVE/Assets/Scripts/Content/Skill/BaseSkill.cs
HIGHFIVE/Assets/Scripts/Content/Skill/CharacterSkill.cs
HIGHFIVE/Assets/Scripts/Content/Skill/Mage/FireBall.cs
HIGHFIVE/Assets/Scripts/Content/Skill/Mage/MageSkills.cs
HIGHFIVE/Assets/Scripts/Content/Skill/SkillTimer.cs
HIGHFIVE/Assets/Scripts/UI/Scene_UI/SkillScene_UI.cs
HIGHFIVE/Assets/Scripts/UI/Scene_UI/SkillScene_UI.cs.meta

[Feat] Skill Cool UI

---

HIGHFIVE/Assets/Plugins/Borodar/RainbowFolders/Editor/Source/RainbowFolders.src.unitypackage.meta
HIGHFIVE/Assets/Scripts/Utils/LoadingAnimation.cs

하드코딩으로 되어있던 totalCount를 enum을 통해서 전체를 구하도록함.

[Fix] LoadingScene totalCount

---

HIGHFIVE/Assets/Plugins/Borodar/RainbowFolders/Editor/Source/RainbowFolders.src.unitypackage.meta
HIGHFIVE/Assets/Scripts/Controller/BuffController/BuffController.cs
HIGHFIVE/Assets/Scripts/UI/Scene_UI/SelectScene_Timer.cs
HIGHFIVE/Assets/Scripts/Utils/LoadingAnimation.cs

[Feat] Sync GameScene Load

---

HIGHFIVE/Assets/Plugins/Borodar/RainbowFolders/Editor/Source/RainbowFolders.src.unitypackage.meta
HIGHFIVE/Assets/Scripts/Utils/LoadingAnimation.cs

[Mod] Loading Bar

---

HIGHFIVE/Assets/Resources/Prefabs/UI_Prefabs/GameSceneUI.prefab
HIGHFIVE/Assets/Resources/Sprites/UI/ButtomSkill.png.meta
HIGHFIVE/Assets/Scripts/Content/Skill/Rogue/Assassination.cs

도적스킬 암살 임시데이터 입력
게임씬 아래 이미지 UI 크기 조정

[Mod] GameSceneUI sprite size, assassination data enter

---

HIGHFIVE/Assets/Resources/Prefabs/Character/Warrior.prefab
HIGHFIVE/Assets/Scripts/Content/Buff/AssassinationBuff.cs
HIGHFIVE/Assets/Scripts/Content/Buff/BaseBuff.cs
HIGHFIVE/Assets/Scripts/Content/Buff/LoserBuff.cs
HIGHFIVE/Assets/Scripts/Content/Buff/StabbingBuff.cs
HIGHFIVE/Assets/Scripts/Content/Skill/Rogue/Assassination.cs
HIGHFIVE/Assets/Scripts/Content/Skill/Warrior/Stabbing.cs
HIGHFIVE/Assets/Scripts/Content/Skill/Warrior/WarriorSkill.cs
HIGHFIVE/Assets/Scripts/Content/Stat/Stat.cs
HIGHFIVE/Assets/Scripts/Controller/BuffController/BuffController.cs
HIGHFIVE/Assets/Scripts/Controller/StatController.cs
HIGHFIVE/Assets/Scripts/Object/Character/Character.cs
HIGHFIVE/Assets/Scripts/Object/Character/Warrior.cs
HIGHFIVE/Assets/Scripts/UI/GameScene_UI/RoundLogic.cs
HIGHFIVE/Assets/Scripts/UI/Scene_UI/BuffScene_UI.cs
HIGHFIVE/Assets/Scripts/Utils/LoadingAnimation.cs

패자의 분노, 암살 디버프 버그 수정
워리어 스킬 추가

[Fix & Feat] Loser Buff, Assessination Buff & Warrior Skill

---

HIGHFIVE/Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
HIGHFIVE/Assets/Scenes/06.GameScene.unity
HIGHFIVE/Assets/Scripts/Content/Buff/AssassinationBuff.cs
HIGHFIVE/Assets/Scripts/Content/Buff/BaseBuff.cs
HIGHFIVE/Assets/Scripts/Content/Buff/StabbingBuff.cs
HIGHFIVE/Assets/Scripts/Content/Buff/StunShotBuff.cs
HIGHFIVE/Assets/Scripts/Content/Skill/Rogue/Assassination.cs
HIGHFIVE/Assets/Scripts/Controller/BuffController/BuffController.cs
HIGHFIVE/Assets/Scripts/UI/GameScene_UI/RoundLogic.cs
HIGHFIVE/Assets/Scripts/UI/GameScene_UI/RoundTimer.cs

게임 시작시 라운드가 2로 시작하는 버그 수정
도적의 암살 스킬 디버프로 몬스터를 죽였을 때 경험치가 안들어오는 버그 수정
베틀에서 파밍 & 파밍에서 베틀로 넘어 갈 때 워리어의 버서커 버프가 없어지는 버그 수정

[Fix] Round & Exp & ChangeRound

---

HIGHFIVE/Assets/Scripts/Content/Buff/AssassinationBuff.cs
HIGHFIVE/Assets/Scripts/Content/Buff/LoserBuff.cs
HIGHFIVE/Assets/Scripts/Content/Buff/StabbingBuff.cs
HIGHFIVE/Assets/Scripts/Content/Buff/StunShotBuff.cs
HIGHFIVE/Assets/Scripts/Content/Skill/CommonSkill/Flash.cs
HIGHFIVE/Assets/Scripts/Content/Skill/CommonSkill/StunShot.cs
HIGHFIVE/Assets/Scripts/Content/Skill/Mage/FireBall.cs
HIGHFIVE/Assets/Scripts/Content/Skill/Rogue/Assassination.cs
HIGHFIVE/Assets/Scripts/Content/Skill/Warrior/Stabbing.cs
HIGHFIVE/Assets/Scripts/Data/BuffDBEntity.cs
HIGHFIVE/Assets/Scripts/Data/SkillDBEntity.cs
HIGHFIVE/Assets/Scripts/Object/Projectile/FireBallProjectile.cs

[Fix] Exel Data

---

HIGHFIVE/Assets/Resources/Data/HIGHFIVE_Data.asset
HIGHFIVE/Assets/Scripts/Content/Stat/Character/CharacterStat.cs

[Mod] Character Level Stat

---

HIGHFIVE/Assets/Resources/Prefabs/Monster/Elite/Elite_BossOrc.prefab
HIGHFIVE/Assets/Scenes/06.GameScene.unity

[Mod] MonsterPosition

---

HIGHFIVE/Assets/Elite_BossOrc_Spawner.cs
HIGHFIVE/Assets/Epic_BlueOrc_Spawner.cs
HIGHFIVE/Assets/Epic_RedOrc_Spawner.cs
HIGHFIVE/Assets/Scenes/06.GameScene.unity
HIGHFIVE/Assets/Scripts/Object/Monster/Spawner/MonsterSpawner.cs
HIGHFIVE/Assets/Scripts/Object/Monster/Spawner/Normal_GreenOrc1_Spawner.cs
HIGHFIVE/Assets/Scripts/Object/Monster/Spawner/Normal_GreenOrc2_Spawner.cs
HIGHFIVE/Assets/Scripts/Object/Monster/Spawner/Normal_Tree_Spawner.cs
HIGHFIVE/Assets/Scripts/Object/Projectile/FireBallProjectile.cs

[Fix] Monster Number

---

HIGHFIVE/Assets/Resources/Animations/SkillEffectAnim/FireballAnim.anim
HIGHFIVE/Assets/Resources/Animations/SkillEffectAnim/FireballAnim.anim.meta
HIGHFIVE/Assets/Resources/Animations/SkillEffectController/FireBallContorller.controller
HIGHFIVE/Assets/Resources/Animations/SkillEffectController/FireBallContorller.controller.meta
HIGHFIVE/Assets/Resources/Prefabs/SkillEffect/FireBallEffect.prefab

[Mod] FireBall Animation

---

HIGHFIVE/Assets/Resources/Animations/SkillEffectAnim/FireBallDefault.anim
HIGHFIVE/Assets/Resources/Animations/SkillEffectAnim/FireBallDefault.anim.meta
HIGHFIVE/Assets/Resources/Animations/SkillEffectController/FireBallContorller.controller
HIGHFIVE/Assets/Resources/Prefabs/SkillEffect/FireBallEffect.prefab
HIGHFIVE/Assets/Scripts/Content/SkillEffect/FireBallEffect.cs
HIGHFIVE/Assets/Scripts/Content/SkillEffect/FireBallEffect.cs.meta
HIGHFIVE/Assets/Scripts/Object/Projectile/FireBallProjectile.cs

[Feat] FireBall Anim

---

HIGHFIVE/Assets/Scenes/06.GameScene.unity
HIGHFIVE/Assets/Scripts/Managers/SoundManager.cs

- 맵 뒷배경이 일부 잘리는 현상 수정
- 배경음악 loop 설정 (모든 씬에서)

[Mod] Map background, BGM

---

HIGHFIVE/Assets/Resources/Animations/CharacterController/MageAnimController.controller
HIGHFIVE/Assets/Scenes/02.LobbyScene.unity
HIGHFIVE/Assets/Scripts/Content/Buff/StunShotBuff.cs
HIGHFIVE/Assets/Scripts/Content/Skill/CommonSkill/StunShot.cs
HIGHFIVE/Assets/Scripts/Object/Projectile/StunShotProjectile.cs
HIGHFIVE/Assets/Scripts/UI/Popup_UI/SetRoomUI.cs
HIGHFIVE/Assets/Scripts/UI/Scene_UI/LobbyScene_UI.cs
HIGHFIVE/Assets/Scripts/UI/Scene_UI/PlayerReadyController.cs
HIGHFIVE/Assets/Scripts/UI/Scene_UI/RoomScene_UI.cs
HIGHFIVE/Assets/Scripts/UI/World_UI/HealthBar.cs
HIGHFIVE/Assets/Scripts/Utils/Define.cs

포톤과의 동작과 관련된 버튼들 더블 클릭시 오류 뜨는 부분 수정
막타로 스턴샷을 맞으면 죽는 상태가 아닌 스턴상태로 되는 버그 수정

[Fix] Button DoubleClick  & StunShot

---

HIGHFIVE/Assets/Plugins/Borodar/RainbowFolders/Editor/Source/RainbowFolders.src.unitypackage.meta
HIGHFIVE/Assets/Scripts/Object/Character/Character.cs

디버프를 걸었을 때 다른플레이어 쪽에서 Null뜨는 오류 수정

[Fix] Debuff

---

HIGHFIVE/Assets/Resources/Prefabs/UI_Prefabs/GameSceneUI.prefab
HIGHFIVE/Assets/Resources/Prefabs/UI_Prefabs/Skill.prefab
HIGHFIVE/Assets/Resources/Sprites/BuffIcon/Blue.png.meta
HIGHFIVE/Assets/Scripts/Content/Buff/AssassinationBuff.cs
HIGHFIVE/Assets/Scripts/Content/Skill/CharacterSkill.cs
HIGHFIVE/Assets/Scripts/Content/Skill/CommonSkill/Flash.cs
HIGHFIVE/Assets/Scripts/Content/Skill/CommonSkill/StunShot.cs
HIGHFIVE/Assets/Scripts/Content/Skill/Mage/FireBall.cs
HIGHFIVE/Assets/Scripts/Content/Skill/Rogue/Assassination.cs
HIGHFIVE/Assets/Scripts/Content/Skill/Warrior/Stabbing.cs
HIGHFIVE/Assets/Scripts/Object/Character/Character.cs
HIGHFIVE/Assets/Scripts/State/Character/PlayerDieState.cs
HIGHFIVE/Assets/Scripts/UI/Scene_UI/SkillExplan_UI.cs
HIGHFIVE/Assets/Scripts/UI/Scene_UI/SkillScene_UI.cs

[Feat] Skill Info ToolTip
